theme: jekyll-theme-hacker
title: 
description: 

# Optional features
show_related_posts: true
show_post_footers: true
show_subscribe_cta: false
show_social_icons: true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Social icons
github_username: danijelst
